export {
  bonusApi,
  useRedeemPromoMutation,
  useGetCashbackQuery,
  useClaimCashbackMutation,
  useGetBonusNotificationsQuery,
  useGetBonusOverviewQuery,
  useGetBonusChoiceQuery,
  usePutBonusChoiceMutation,
} from './api/bonusApi';
export type {
  RedeemPromoRequest,
  CashbackResponse,
  CashbackInfo,
  CashbackStatus,
  CashbackClaimable,
  ClaimCashbackRequest,
  BonusNotificationsResponse,
  PromoResponse,
  BonusRedeemResponseWeb,
  FreespinsRedeemResponseWeb,
  DepositReserveFundsWeb,
  DepositReservePercentWeb,
  DepositReserveFreespinsWeb,
  ISlots,
} from './model';
