export {
  walletApi,
  useGetWalletDepositMethodsQuery,
  useGetWalletWithdrawMethodsQuery,
  useGetWalletWithdrawBanksQuery,
  useGetWalletTransactionsQuery,
  useLazyGetWalletTransactionsQuery,
  useGetWalletTransactionByUuidQuery,
  useLazyGetWalletTransactionByUuidQuery,
} from './api/walletApi';
export type {
  WalletDepositMethodsResponse,
  FiatDepositMethod,
  CryptoDepositMethod,
  TelegramDepositMethod,
  TelegramAsset,
  WalletWithdrawMethodsResponse,
  FiatWithdrawMethod,
  CryptoWithdrawMethod,
  TelegramWithdrawMethod,
  TelegramWithdrawAsset,
  Currency,
  Media,
  Field,
  Fee,
  WalletWithdrawBanksResponse,
  WalletWithdrawBank,
  WalletTransaction,
  WalletTransactionsResponse,
  GetWalletTransactionsParams,
  WalletTransactionRequisitesTelegram,
  WalletTransactionRequisitesCryptoStatic,
  WalletTransactionRequisitesFiat,
} from './model';
