export {
  showcaseApi,
  useGetShowcaseGamesQuery,
  useLazyGetShowcaseGamesQuery,
  useGetBettingTableBetsLatestQuery,
  useGetBettingTableBetsMyQuery,
  useGetBettingTableBetsBigWinsQuery,
  useGetSlotInfoQuery,
  useGetSlotLeaderboardBigWinsQuery,
  useGetSlotLeaderboardLuckyQuery,
  useGetSlotLeaderboardTodayBestQuery,
  useInitSlotMutation,
  useInitSlotDemoMutation,
  useAddFavoriteMutation,
  useRemoveFavoriteMutation,
} from './api/showcaseApi';
export type {
  ShowcaseGamesResponse,
  GetShowcaseGamesParams,
  BettingTableBetsLatestResponse,
  GetBettingTableBetsLatestParams,
  BettingTableBetsMeta,
  ShowcaseGamesMeta,
  SortType,
  SortDirection,
  GetSlotInfoParams,
  GetSlotInfoResponse,
  GetSlotLeaderboardBigWinsParams,
  GetSlotLeaderboardBigWinsResponse,
  SlotLeaderboardBigWinItem,
  GetSlotLeaderboardLuckyParams,
  GetSlotLeaderboardLuckyResponse,
  SlotLeaderboardLuckyItem,
  GetSlotLeaderboardTodayBestParams,
  GetSlotLeaderboardTodayBestResponse,
  SlotLeaderboardTodayBestItem,
  InitSlotParams,
  InitSlotResponse,
  InitSlotDemoParams,
  InitSlotDemoResponse,
  AddFavoriteParams,
  AddFavoriteResponse,
  RemoveFavoriteParams,
  RemoveFavoriteResponse,
} from './model';
