export {
  showcaseApi,
  useGetShowcaseGamesQuery,
  useLazyGetShowcaseGamesQuery,
  useGetBettingTableBetsLatestQuery,
  useGetBettingTableBetsMyQuery,
  useGetBettingTableBetsBigWinsQuery,
  useInitSlotMutation,
  useInitSlotDemoMutation,
  useAddFavoriteMutation,
  useRemoveFavoriteMutation,
} from './api/showcaseApi';
export type {
  ShowcaseGamesResponse,
  GetShowcaseGamesParams,
  BettingTableBetsLatestResponse,
  GetBettingTableBetsLatestParams,
  BettingTableBetsMeta,
  ShowcaseGamesMeta,
  SortType,
  SortDirection,
  InitSlotParams,
  InitSlotResponse,
  InitSlotDemoParams,
  InitSlotDemoResponse,
  AddFavoriteParams,
  AddFavoriteResponse,
  RemoveFavoriteParams,
  RemoveFavoriteResponse,
} from './model';
