export type {
  RedeemPromoRequest,
  CashbackResponse,
  CashbackInfo,
  CashbackStatus,
  CashbackClaimable,
  ClaimCashbackRequest,
  ClaimCashbackResponse,
  BonusNotificationsResponse,
  PromoResponse,
  BonusRedeemResponseWeb,
  FreespinsRedeemResponseWeb,
  DepositReserveFundsWeb,
  DepositReservePercentWeb,
  DepositReserveFreespinsWeb,
  RedeemPromoError,
  RedeemPromoErrorData,
  RedeemPromoErrorDetail,
  RedeemPromoErrorDetailObject,
  CurrentPromo,
} from './types';
